const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='statisticsOS.exam.v3';
const defaults={theme:'light',examDate:'',answers:{},favorites:[],simulations:[]};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem(STORE)||'{}'));
const CHAPTER_TOPIC={12:'chi-square',13:'anova',14:'simple-regression',15:'multiple-regression',16:'model-building',17:'forecasting',18:'nonparametric'};
const BANK=FULL_QUESTIONS.map(q=>Object.assign({},q,{topic:CHAPTER_TOPIC[q.chapter]},VERIFIED_ANSWERS[q.id]||{}));
let activeTopic=TOPICS[0].id,activeQuestion=BANK[0].id,selectedAnswer=null,simulation=null,timer=null;
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
const topic=id=>TOPICS.find(t=>t.id===id), question=id=>BANK.find(q=>q.id===id);
const formulaHTML=s=>String(s||'').split('\n').map(x=>`\\(${x}\\)`).join('<br>');
const typeset=()=>window.MathJax?.typesetPromise?.().catch(()=>{});

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
function setTheme(v){state.theme=v;document.documentElement.dataset.theme=v;$('#themeBtn').textContent=v==='dark'?'☀':'☾';save()}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.view===id));$('#sidebar').classList.remove('open');history.replaceState(null,'','#'+id);window.scrollTo({top:0,behavior:'smooth'});if(id==='dashboard')renderDashboard();if(id==='practice')renderPractice()}
function attempts(){return Object.values(state.answers)}
function topicStats(id){const qs=BANK.filter(q=>q.topic===id),done=qs.filter(q=>state.answers[q.id]),correct=qs.filter(q=>state.answers[q.id]?.correct);return{total:qs.length,done:done.length,correct:correct.length,pct:qs.length?Math.round(done.length/qs.length*100):0}}
function verifiedCount(){return BANK.filter(q=>q.status==='verified').length}

function renderDashboard(){
  const a=attempts(),done=Object.keys(state.answers).length,correct=a.filter(x=>x.correct).length,wrong=a.filter(x=>!x.correct).length;
  $('#completedMetric').textContent=done;$('#totalMetric').textContent=BANK.length;$('#accuracyMetric').textContent=a.length?Math.round(correct/a.length*100)+'%':'—';$('#attemptMetric').textContent=a.length?`${a.length} 次作答`:`${verifiedCount()} 題答案已驗證`;$('#wrongMetric').textContent=wrong;$('#favoriteMetric').textContent=state.favorites.length;
  const overall=Math.round(done/BANK.length*100);$('#sideProgressText').textContent=overall+'%';$('#sideProgress').style.width=overall+'%';
  const next=TOPICS.slice().sort((x,y)=>({S:0,A:1,B:2}[x.priority]-{S:0,A:1,B:2}[y.priority])||topicStats(x.id).pct-topicStats(y.id).pct)[0];$('#nextTopic').textContent=`${next.title} · ${next.zh}`;$('#nextReason').textContent=`完整題庫 ${topicStats(next.id).total} 題；目前完成 ${topicStats(next.id).done} 題。`;$('#nextAction').dataset.topic=next.id;
  $('#priorityList').innerHTML=TOPICS.map(t=>`<div class="priority-row"><span class="priority-badge ${t.priority}">${t.priority}</span><div><b>${t.title}</b><small>Ch ${t.chapter} · ${t.zh}</small></div><small>${topicStats(t.id).done}/${topicStats(t.id).total}</small></div>`).join('');
  const max=Math.max(...TOPICS.map(t=>t.sourceCount));$('#frequencyChart').innerHTML=TOPICS.map(t=>`<div class="bar-row"><span>Ch ${t.chapter}</span><div class="bar-track"><div class="bar" style="width:${t.sourceCount/max*100}%"></div></div><b>${t.sourceCount}</b></div>`).join('');
  $('#topicProgress').innerHTML=TOPICS.map(t=>{const s=topicStats(t.id);return`<div class="topic-progress"><p><b>${t.title}</b><span>${s.pct}%</span></p><div class="progress"><i style="width:${s.pct}%"></i></div><small>${s.done}/${s.total} 題完成</small></div>`}).join('');renderCountdown();
}
function renderCountdown(){if(!state.examDate){$('#countdown').textContent='尚未設定';return}const days=Math.ceil((new Date(state.examDate+'T23:59:59')-new Date())/864e5);$('#countdown').textContent=days<0?'考試已結束':days===0?'就是今天':`${days} 天`}

function renderTopicTabs(){$('#topicTabs').innerHTML=TOPICS.map(t=>`<button class="topic-tab ${t.id===activeTopic?'active':''}" data-topic="${t.id}">Ch ${t.chapter} · ${t.title}</button>`).join('')}
function renderTopic(id){activeTopic=id;const t=topic(id);renderTopicTabs();$('#topicDetail').innerHTML=`<article class="card topic-hero"><div class="topic-hero-top"><div><span class="label">CHAPTER ${t.chapter}</span><h2>${t.title} <small>${t.zh}</small></h2></div><div class="badges"><span class="badge priority-${t.priority}">${t.priority} 級必考</span><span class="badge">完整題庫 ${topicStats(t.id).total} 題</span></div></div><div class="topic-path">Statistics System / ${t.position}</div><div class="business-callout"><span class="label">BUSINESS QUESTION</span><div>${t.business}</div></div></article><div class="knowledge-grid"><article class="card knowledge-card"><h3>Input → Process → Output</h3><p><b>處理目標：</b>${t.target}</p><p><b>資料結構：</b>${t.samples}</p><ul class="condition-list">${t.conditions.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="card knowledge-card"><h3>公式不是起點</h3><p>${t.intuition}</p><div class="formula-box">${formulaHTML(t.formula)}</div><p><span class="label">EXCEL</span><br>${t.excel.replaceAll('\n','<br>')}</p></article><article class="card knowledge-card"><h3>題目辨認器</h3><div class="keyword-list">${t.keywords.map(x=>`<span class="keyword">${x}</span>`).join('')}</div><p><b>Professor trap</b></p><p>${t.trap}</p></article><article class="card knowledge-card mini-quiz"><h3>迷你練習</h3><p>${t.mini.q}</p>${t.mini.options.map((x,i)=>`<button data-mini="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}<div class="mini-feedback" id="miniFeedback"></div></article></div>`;typeset()}

const DECISION={root:{q:'題目主要要你做什麼？',o:[['比較類別分配／關聯','category'],['比較平均數','means'],['解釋或預測數值 Y','predict'],['資料不適合母數方法','rank']]},category:{q:'有幾個類別變數？',o:[['一個：和指定比例比較','chi-square'],['兩個：是否有關聯','chi-square']]},means:{q:'要比較幾組平均數？',o:[['三組以上','anova'],['有 treatment 與 block','anova']]},predict:{q:'資料有時間順序嗎？',o:[['有，預測未來','forecasting'],['沒有，只有一個 X','simple-regression'],['沒有，有多個 X','multiple-regression'],['重點是選模與診斷','model-building']]},rank:{q:'樣本結構？',o:[['成對／前後測','nonparametric'],['兩獨立組','nonparametric'],['排名的一致程度','nonparametric']]}};
function renderDecision(node='root'){const d=DECISION[node];$('#decisionQuestion').textContent=d.q;$('#decisionOptions').innerHTML=d.o.map(x=>`<button data-next="${x[1]}">${x[0]}</button>`).join('');$('#decisionResult').style.display='none'}

function parseMC(text){const matches=[...text.matchAll(/(?:^|\n)\s*([a-d])\.\s*([\s\S]*?)(?=(?:\n\s*[a-d]\.\s)|$)/gi)];if(matches.length<2)return null;const first=matches[0].index||0;return{stem:text.slice(0,first).trim(),options:matches.map(m=>m[2].trim())}}
function filteredQuestions(){const chapter=$('#filterChapter').value,section=$('#filterSection').value,num=$('#filterNumber').value,status=$('#filterAnswerStatus').value;return BANK.filter(q=>(chapter==='all'||q.chapter===+chapter)&&(section==='all'||q.section===section)&&(!num||q.number===+num)&&($('#filterTopic').value==='all'||q.topic===$('#filterTopic').value)&&(status==='all'||(q.status||q.answerStatus)===status)&&(!$('#filterWrong').checked||state.answers[q.id]&&!state.answers[q.id].correct)&&(!$('#filterFavorite').checked||state.favorites.includes(q.id))&&(!$('#filterIncomplete').checked||!state.answers[q.id]))}
function renderQuestionList(){const qs=filteredQuestions();if(!qs.some(q=>q.id===activeQuestion))activeQuestion=qs[0]?.id;$('#questionList').innerHTML=qs.length?`<div class="bank-summary"><span class="badge">${qs.length} 題</span></div>`+qs.map(q=>`<button class="${q.id===activeQuestion?'active':''}" data-question="${q.id}"><b>Ch${q.chapter} · ${q.section==='Multiple Choice'?'MC':'P'} ${q.number}</b><small>PDF p.${q.page} · ${(q.status||q.answerStatus)==='verified'?'✓ 已驗證':'待驗證'}</small></button>`).join(''):'<p>沒有符合條件的題目。</p>';renderQuestion(activeQuestion)}
function renderQuestionListActive(){$$('#questionList button').forEach(b=>b.classList.toggle('active',b.dataset.question===activeQuestion))}

function renderQuestion(id){
  const q=question(id);if(!q){$('#questionWorkspace').innerHTML='<div class="card question-card">請調整篩選條件。</div>';return}activeQuestion=id;selectedAnswer=null;const old=state.answers[id],mc=parseMC(q.text),verified=q.status==='verified';
  const answerUI=verified&&q.section==='Multiple Choice'&&mc?`<div class="options">${mc.options.map((x,i)=>`<button class="option" data-option="${String.fromCharCode(65+i)}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}</div><button class="primary" id="submitAnswer">提交答案</button>`:`<label><span class="label">CALCULATION SCRATCHPAD</span><textarea class="scratch" id="scratch" placeholder="寫下 H₀、df、公式或計算步驟…"></textarea></label>${verified?'<button class="primary" id="revealAnswer">查看已驗證答案</button>':'<div class="answer-status pending">本題答案尚未完成獨立驗算，因此不顯示推測答案。</div>'}`;
  $('#questionWorkspace').innerHTML=`${simulation?`<div class="simulation-bar"><b>模擬考 ${simulation.index+1}/${simulation.ids.length}</b><span id="simTimer"></span></div>`:''}<article class="card question-card"><div class="question-meta"><span class="badge bank-number">CH${q.chapter} · ${q.section==='Multiple Choice'?'MC':'PROBLEM'} · ${q.number}</span><span class="badge">${q.source} · PDF p.${q.page}</span><span class="badge ${(verified?'confidence-high':'confidence-medium')}">${verified?'✓ 答案已重新驗證':'待驗證'}</span></div><h2>${q.section} ${q.number}</h2>${q.exhibit?`<div class="exhibit-box">${q.exhibit}</div>`:''}<pre class="question-text source-question">${q.text}</pre><div class="question-actions"><a class="text-btn" href="sources/ch${q.chapter}-question-set.pdf#page=${q.page}" target="_blank" rel="noopener">開啟原始 PDF 第 ${q.page} 頁 ↗</a><button class="favorite ${state.favorites.includes(id)?'on':''}" data-favorite="${id}">★ 收藏</button></div>${answerUI}<div class="explanation ${old&&verified&&!simulation?'show':''}" id="explanation">${old&&verified&&!simulation?answerHTML(q,old.correct):''}</div></article>`;
  if(simulation)updateTimer();renderQuestionListActive();typeset();
}
function answerHTML(q,correct=true){return`<div class="result-banner ${correct?'correct':'wrong'}">${correct?'答案正確／已核對。':'答案不正確。'}</div><h3>Verified answer</h3><div class="original-answer">${q.answer}</div><h3>Recalculation / explanation</h3><div class="original-answer">${q.explanation}</div><p class="confidence-high"><b>Confidence:</b> ${q.confidence==='high'?'High — independently recalculated or definition-checked.':'Medium'}</p>`}
function submitAnswer(){const q=question(activeQuestion);if(selectedAnswer===null){toast('請先選擇答案');return}const correct=selectedAnswer===q.answer;state.answers[q.id]={selected:selectedAnswer,correct,at:new Date().toISOString(),attempts:(state.answers[q.id]?.attempts||0)+1};save();if(simulation){simulation.results.push({id:q.id,correct});if(simulation.index<simulation.ids.length-1){simulation.index++;activeQuestion=simulation.ids[simulation.index];renderQuestion(activeQuestion)}else finishSimulation()}else{$('#explanation').innerHTML=answerHTML(q,correct);$('#explanation').classList.add('show');renderDashboard();renderQuestionList()}}
function revealAnswer(){const q=question(activeQuestion);state.answers[q.id]={selected:'self-check',correct:true,at:new Date().toISOString(),attempts:(state.answers[q.id]?.attempts||0)+1};save();$('#explanation').innerHTML=answerHTML(q,true);$('#explanation').classList.add('show');renderDashboard()}
function locateQuestion(){const ch=$('#filterChapter').value,sec=$('#filterSection').value,num=+$('#filterNumber').value;if(ch==='all'||sec==='all'||!num){toast('請同時選擇 Chapter、題型與題號');return}const q=BANK.find(x=>x.chapter===+ch&&x.section===sec&&x.number===num);if(!q){toast('找不到這個題號');return}activeQuestion=q.id;renderQuestionList();renderQuestion(q.id)}

function renderPractice(){renderQuestionList()}
function startSimulation(){const pool=BANK.filter(q=>q.status==='verified'&&q.section==='Multiple Choice'&&parseMC(q.text)),count=Math.min(+$('#simCount').value,pool.length),mins=+$('#simMinutes').value,ids=pool.slice().sort(()=>Math.random()-.5).slice(0,count).map(q=>q.id);simulation={ids,index:0,results:[],end:Date.now()+mins*60000};activeQuestion=ids[0];$('#simulationModal').classList.remove('open');showView('practice');renderQuestion(activeQuestion);clearInterval(timer);timer=setInterval(updateTimer,1000)}
function updateTimer(){if(!simulation)return;const left=Math.max(0,simulation.end-Date.now()),m=Math.floor(left/60000),s=Math.floor(left%60000/1000),el=$('#simTimer');if(el)el.textContent=`${m}:${String(s).padStart(2,'0')}`;if(!left)finishSimulation()}
function finishSimulation(){clearInterval(timer);const score=simulation.results.filter(x=>x.correct).length,total=simulation.ids.length;state.simulations.push({at:new Date().toISOString(),score,total});save();simulation=null;toast(`模擬考完成：${score}/${total}`);renderDashboard();renderQuestionList()}

function renderStrategy(){$('#methodTable').innerHTML=METHOD_TABLE.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('');$('#mistakeList').innerHTML=COMMON_MISTAKES.map(x=>`<li>${x}</li>`).join('');renderSprint(7)}
function renderSprint(k){$('#sprintPlan').innerHTML=SPRINT_PLANS[k].map(x=>`<li>${x}</li>`).join('');$$('[data-sprint]').forEach(b=>b.classList.toggle('active',b.dataset.sprint==k))}
function renderSources(){$('#sourceList').innerHTML=SOURCES.map(s=>`<div class="source-item"><b>${s[0]}</b><br><small>${s[1]}</small></div>`).join('')+`<div class="source-item"><b>Question bank audit</b><br><small>${BANK.length} questions restored with original English, original chapter, section, number and PDF page. ${verifiedCount()} answers currently carry an independently verified status; all others are visibly marked pending rather than given a guessed answer.</small></div>`}
function init(){setTheme(state.theme);$('#examDate').value=state.examDate;$('#filterTopic').innerHTML+=TOPICS.map(t=>`<option value="${t.id}">Ch ${t.chapter} · ${t.title}</option>`).join('');renderDashboard();renderTopic(activeTopic);renderDecision();renderStrategy();renderSources();renderQuestionList();const hash=location.hash.slice(1);if($(`#${hash}.view`))showView(hash)}

document.addEventListener('click',e=>{
  const nav=e.target.closest('[data-view]');if(nav){e.preventDefault();showView(nav.dataset.view)}
  const go=e.target.closest('[data-go]');if(go)showView(go.dataset.go);
  const tt=e.target.closest('[data-topic]');if(tt)renderTopic(tt.dataset.topic);
  const mini=e.target.closest('[data-mini]');if(mini){const t=topic(activeTopic),fb=$('#miniFeedback');fb.style.display='block';fb.textContent=(+mini.dataset.mini===t.mini.answer?'正確。':'不對。')+t.mini.why}
  const dn=e.target.closest('[data-next]');if(dn){if(DECISION[dn.dataset.next])renderDecision(dn.dataset.next);else{const t=topic(dn.dataset.next),r=$('#decisionResult');r.style.display='block';r.innerHTML=`建議方法：<b>${t.title} · ${t.zh}</b>　<button class="text-btn" data-open-topic="${t.id}">查看主題 →</button>`}}
  const open=e.target.closest('[data-open-topic]');if(open)renderTopic(open.dataset.openTopic);
  const ql=e.target.closest('[data-question]');if(ql){activeQuestion=ql.dataset.question;renderQuestion(activeQuestion)}
  const opt=e.target.closest('[data-option]');if(opt){selectedAnswer=opt.dataset.option;$$('.option').forEach(x=>x.classList.toggle('selected',x===opt))}
  if(e.target.id==='submitAnswer')submitAnswer();if(e.target.id==='revealAnswer')revealAnswer();
  const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();fav.classList.toggle('on');renderDashboard()}
  if(e.target.closest('[data-close]'))$('#simulationModal').classList.remove('open');const sp=e.target.closest('[data-sprint]');if(sp)renderSprint(sp.dataset.sprint);
});
['filterChapter','filterSection','filterTopic','filterAnswerStatus','filterWrong','filterFavorite','filterIncomplete'].forEach(id=>$(`#${id}`).addEventListener('change',renderQuestionList));
$('#filterNumber').addEventListener('input',renderQuestionList);$('#locateQuestion').addEventListener('click',locateQuestion);
$('#clearFilters').addEventListener('click',()=>{$('#filterChapter').value=$('#filterSection').value=$('#filterTopic').value=$('#filterAnswerStatus').value='all';$('#filterNumber').value='';$('#filterWrong').checked=$('#filterFavorite').checked=$('#filterIncomplete').checked=false;renderQuestionList()});
$('#examDate').addEventListener('change',e=>{state.examDate=e.target.value;save();renderCountdown()});$('#nextAction').addEventListener('click',e=>{activeTopic=e.currentTarget.dataset.topic;showView('knowledge');renderTopic(activeTopic)});$('#resetDecision').addEventListener('click',()=>renderDecision());
$('#simulationBtn').addEventListener('click',()=>$('#simulationModal').classList.add('open'));$('#startSimulation').addEventListener('click',startSimulation);$('#themeBtn').addEventListener('click',()=>setTheme(state.theme==='light'?'dark':'light'));$('#themeSetting').addEventListener('click',()=>setTheme(state.theme==='light'?'dark':'light'));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#copyTemplate').addEventListener('click',()=>navigator.clipboard.writeText($('.answer-template').innerText).then(()=>toast('作答模板已複製')).catch(()=>toast('請手動選取模板')));$('#exportData').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='statistics-os-progress.json';a.click();URL.revokeObjectURL(a.href)});$('#resetData').addEventListener('click',()=>{if(confirm('確定清除所有學習紀錄？')){localStorage.removeItem(STORE);location.reload()}});
$('#globalSearch').addEventListener('input',e=>{const s=e.target.value.trim().toLowerCase();if(!s)return;const found=BANK.find(q=>(q.text+' '+q.exhibit+' '+q.source).toLowerCase().includes(s));if(found){activeQuestion=found.id;showView('practice');renderQuestion(found.id)}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});
init();
