/* Statistics OS content database. UI logic lives in app.js. */
const TOPICS = [
  {id:'chi-square',chapter:12,title:'Chi-square Tests',zh:'卡方檢定',priority:'S',sourceCount:82,position:'Inferential Statistics → Categorical Data → Frequency Comparison',target:'分類／比例',samples:'一個類別變數，或兩個類別變數',business:'顧客偏好是否符合預期？主修和進入產業是否有關？',conditions:['輸入是互斥類別的 observed counts，不是百分比本身','觀察值彼此獨立','各格期望次數原則上至少 5；過小時需合併合理類別','GOF 若由樣本估計分配參數，df 需再扣除參數數'],keywords:['observed frequency','expected frequency','uniform','independence','contingency table','符合某分配'],formula:'χ² = Σ (O − E)² / E\nGOF df = k − 1 − m\nIndependence df = (r − 1)(c − 1)',excel:'=CHISQ.TEST(actual_range, expected_range)\n=CHISQ.INV.RT(alpha, df)',intuition:'把每格「實際－應有」的差距，除以該格合理尺度後加總。差距越大，越反對 H₀。',trap:'卡方一定是右尾；原始資料可以是數字，關鍵是最後分析的是類別次數。',mini:{q:'性別 × 飲料偏好要檢定是否有關，使用哪一種？',options:['Chi-square independence','Goodness-of-fit','ANOVA'],answer:0,why:'兩個類別變數形成列聯表，使用獨立性檢定。'}},
  {id:'anova',chapter:13,title:'ANOVA',zh:'變異數分析',priority:'S',sourceCount:115,position:'Inferential Statistics → Mean Comparison → 3+ Groups',target:'平均數／變異分解',samples:'三組以上獨立樣本；或 treatment × block',business:'四種生產方案的平均產出是否相同？控制批次後製程是否仍有差異？',conditions:['依變數為數值型，factor 為類別型','各觀察值獨立','各母體近似常態；對等樣本量通常較穩健','母體變異數同質；題目通常明示或要求假設'],keywords:['three or more means','treatments','ANOVA table','between / within','Fisher LSD','block'],formula:'SST = SSTR + SSE\nMSTR = SSTR/(k−1)\nMSE = SSE/(n−k)\nF = MSTR/MSE',excel:'=F.DIST.RT(F, df1, df2)\n資料 → 資料分析 → ANOVA: Single Factor',intuition:'F 是「組間訊號 ÷ 組內噪音」。F 很大代表組平均差距不像只是隨機波動。',trap:'整體 F 顯著只代表至少一組不同；必須再用 LSD 等 post hoc 才知道哪一組。MS 不是普通 mean。',mini:{q:'ANOVA 得 p=.01，第一個正確結論是？',options:['至少一個母體平均數不同','每一組平均數都不同','最大樣本平均就是最佳方案'],answer:0,why:'Omnibus F test 只能推論「不全相等」。'}},
  {id:'simple-regression',chapter:14,title:'Simple Regression',zh:'簡單線性迴歸',priority:'S',sourceCount:146,position:'Inferential Statistics → Relationship → One Predictor',target:'關係／預測',samples:'一個數值 Y 與一個數值 X',business:'價格每增加 1 元，銷量平均改變多少？頁數能否預測書價？',conditions:['線性關係','誤差獨立','誤差變異數固定','推論時通常假設誤差近似常態'],keywords:['slope','least squares','predict','correlation','R-squared','residual'],formula:'ŷ = b₀ + b₁x\ne = y − ŷ\nR² = SSR/SST = 1 − SSE/SST',excel:'=SLOPE(y_range,x_range)\n=INTERCEPT(y_range,x_range)\n=RSQ(y_range,x_range)\n=FORECAST.LINEAR(x,y_range,x_range)',intuition:'迴歸線是在所有直線中，使殘差平方和 SSE 最小的那一條。',trap:'相關與迴歸不代表因果；高 R² 不保證殘差型態合理，也不授權超出資料範圍外插。',mini:{q:'實際銷售 120、模型預測 110，residual 是？',options:['10','−10','230'],answer:0,why:'e = actual − predicted = 120 − 110。'}},
  {id:'multiple-regression',chapter:15,title:'Multiple Regression',zh:'複迴歸',priority:'S',sourceCount:115,position:'Inferential Statistics → Relationship → Multiple Predictors',target:'關係／控制其他變數',samples:'一個數值 Y 與兩個以上 X',business:'控制廣告後，增加一位業務員是否仍提升銷售？整體模型能否解釋 Y？',conditions:['延續線性迴歸的誤差假設','X 之間不可有嚴重多重共線性','個別 t 與整體 F 回答不同問題','解讀係數時其餘 predictors 固定'],keywords:['multiple regression','individual coefficient','overall F','adjusted R²','dummy variable'],formula:'ŷ = b₀ + b₁x₁ + … + bₚxₚ\ntⱼ = bⱼ/s(bⱼ)\nF = MSR/MSE',excel:'資料 → 資料分析 → Regression\n=T.DIST.2T(ABS(t), df)\n=F.DIST.RT(F, p, n−p−1)',intuition:'每個 slope 是在其他 X 固定後，該 X 對 Y 的邊際線性關係。',trap:'整體 F 顯著不代表每個係數都顯著；R² 幾乎只升不降，跨模型優先看 adjusted R²。',mini:{q:'模型整體 F 顯著，但 X₂ 的 p=.64，正確解讀？',options:['模型有解釋力，但 X₂ 在控制其他 X 後不顯著','所有 X 都顯著','模型一定有因果'],answer:0,why:'整體 F 與個別 t 的虛無假設不同。'}},
  {id:'model-building',chapter:16,title:'Model Construction',zh:'模型建構',priority:'A',sourceCount:77,position:'Regression → Diagnostics & Selection → Final Model',target:'選模／診斷',samples:'巢狀迴歸模型、時間順序殘差、類別 predictors',business:'新增競品價格真的改善模型嗎？殘差是否有彎曲或自相關？',conditions:['新增變數檢定只比較 nested models','二次項與交互作用需保留階層原則','選模後仍需檢查 residual plot','時間資料需檢查 error independence'],keywords:['add variable','partial F','quadratic','interaction','stepwise','Durbin-Watson'],formula:'Partial F = [(SSEᵣ−SSE𝒻)/(p𝒻−pᵣ)] / [SSE𝒻/(n−p𝒻−1)]\nd = Σ(eₜ−eₜ₋₁)² / Σeₜ²',excel:'回歸分兩次取得 SSE，再手算 Partial F\nExcel Regression 的 Residual Output 用於 DW',intuition:'新增變數值得保留，必須使 SSE 的下降相對於新模型殘餘噪音夠大。',trap:'Stepwise/forward/backward 都是 heuristic，不保證真正最佳；DW 落在 dL 與 dU 之間只能說 inconclusive。',mini:{q:'殘差圖呈現 U 型，優先考慮？',options:['加入 x²','提高 α','改做卡方'],answer:0,why:'U 型表示直線遺漏曲率，二次項是合理候選。'}},
  {id:'forecasting',chapter:17,title:'Forecasting',zh:'時間序列與預測',priority:'A',sourceCount:68,position:'Predictive Statistics → Time Series → Future Values',target:'時間／未來值',samples:'依時間排列的一個數值序列',business:'下月需求是多少？哪一個平滑係數在驗證期預測較準？',conditions:['保留時間順序，不可隨機打亂','先辨識 level、trend、seasonality、cycle','使用一致的 forecast error 定義','用 MAE/MSE 評估相同尺度的模型'],keywords:['moving average','exponential smoothing','trend','seasonal index','MAE','MSE'],formula:'WMA = Σ(weight × recent value)/Σweight\nFₜ₊₁ = αYₜ + (1−α)Fₜ\nMAE = Σ|e|/n; MSE = Σe²/n',excel:'=SUMPRODUCT(values,weights)/SUM(weights)\n=AVERAGE(range)\n=SUMXMY2(actual,forecast)/n',intuition:'平滑是在「反應速度」與「抗噪音」之間取捨；α 大或窗口小會更靈敏。',trap:'用同一批資料配適得好不代表未來準；移動平均遇到趨勢會 lag，MAPE 遇到 actual=0 失效。',mini:{q:'指數平滑 α 越大，代表？',options:['越重視最新實際值','越重視舊預測','一定越準'],answer:0,why:'α 是最新觀察的權重，不是準確率保證。'}},
  {id:'nonparametric',chapter:18,title:'Nonparametric Methods',zh:'無母數方法',priority:'A',sourceCount:81,position:'Inferential Statistics → Rank/Sign Methods → Fewer Distribution Assumptions',target:'排名／中位位置',samples:'符號、成對排名、兩獨立組排名或排名關聯',business:'滿意度為序位尺度時如何比較？前後測不適合常態假設時怎麼辦？',conditions:['依研究設計區分 paired 與 independent','Sign test 忽略 ties','Signed-rank 的差值分配需大致對稱','Mann–Whitney 若要解讀成中位數差，兩組形狀應相近'],keywords:['sign test','signed-rank','Mann-Whitney','rank sum','Spearman','median'],formula:'Sign test: μ = n/2, σ = √n/2\nSpearman rₛ = 1 − 6Σd²/[n(n²−1)]',excel:'=RANK.AVG(value,range,1)\n=CORREL(rank1_range,rank2_range)\n=NORM.S.DIST(z,TRUE)',intuition:'把原始尺度轉成方向或排名，犧牲部分數值資訊來降低分配假設。',trap:'Nonparametric 不是 assumption-free；Wilcoxon signed-rank 是成對樣本，Mann–Whitney 才是兩獨立樣本。',mini:{q:'同一批顧客改版前後的序位評分，使用？',options:['Wilcoxon signed-rank','Mann–Whitney U','Chi-square GOF'],answer:0,why:'同一批受試者是 paired design。'}}
];

const Q=(id,topic,source,difficulty,priority,type,text,options,answer,steps,formula,excel,statConclusion,businessConclusion,mistakes,confidence='high')=>({id,topic,source,difficulty,priority,type,text,options,answer,steps,formula,excel,statConclusion,businessConclusion,mistakes,confidence});
const QUESTIONS = [
Q('ch12-mc-12','chi-square','Quan1150(Chap12)Q-set.pdf · Exhibit 12-1 / Q12',1,'S','calculation','150 人對議題的意見分成 Yes=40、No=60、No opinion=50。若 H₀ 為三類均勻分配，χ² 統計量是多少？',['2','4','20','50'],1,['均勻分配下每類 E=150/3=50。','χ²=(40−50)²/50+(60−50)²/50+(50−50)²/50。','χ²=2+2+0=4。'],'χ²=Σ(O−E)²/E','=CHISQ.TEST({40,60,50},{50,50,50})','df=2，p≈.135；在 α=.05 不拒絕均勻分配。','樣本不足以顯示三種意見比例與均勻分配不同。',['把比例 1/3 當成 expected count','把卡方當雙尾檢定']),
Q('ch12-ex3','chi-square','Quan1150(Chap12)Q-set.pdf · Problem 3',2,'S','method','吸菸狀態（吸菸／不吸菸）與疾病類型（肺氣腫／心臟問題／癌症）形成 3×2 表。核心應使用哪一種檢定？',['卡方適合度檢定','卡方獨立性檢定','單因子 ANOVA','簡單迴歸'],1,['兩個變數都是類別型。','問題問 illness 是否 independent of smoking。','使用 3×2 contingency table 的 χ² independence test，df=(3−1)(2−1)=2。'],'Eᵢⱼ=(row total×column total)/n','=CHISQ.TEST(observed_range,expected_range)','H₀：疾病與吸菸獨立；H₁：兩者不獨立。','若拒絕 H₀，只能說有關聯，不能直接宣稱吸菸造成特定疾病。',['誤選 GOF','把 association 寫成 causation']),
Q('ch13-assg-ahmadi','anova','Quan1150(Chap13)Q-set.pdf · Problem 20；亦見 Assignment #2 Q4',3,'S','calculation','四個生產力方案各 5 人，樣本平均依序為 A=145、B=135、C=190、D=150。已算得 SSTR=8750、SSE=7600。F 值與 α=.05 結論為何？',['F=2.03，不拒絕 H₀','F=6.14，拒絕 H₀','F=1.84，拒絕 H₀','F=29.22，不拒絕 H₀'],1,['df treatment=4−1=3；df error=20−4=16。','MSTR=8750/3=2916.67；MSE=7600/16=475。','F=2916.67/475=6.14。','Fcrit(3,16,.05)≈3.239，因此拒絕 H₀。'],'F=MSTR/MSE','=F.DIST.RT(6.14035,3,16)','p≈.0056；至少一個方案的母體平均產出不同。','四種方案的平均生產力並非全部相同；還需 post hoc 定位。',['直接說四組全部不同','把 MSE 算成 SSE/(n−1)']),
Q('ch13-lsd','anova','Quan1150(Chap13)Q-set.pdf · Problem 20(d)',3,'A','calculation','沿用四方案題，MSE=475、每組 n=5、df=16。Fisher LSD≈29.22。哪些平均差達顯著？',['只有 C−B','C−A、C−B、C−D','A−B、A−D','所有兩兩差異'],1,['比較每組平均差的絕對值與 29.22。','|C−A|=45、|C−B|=55、|C−D|=40，皆大於 LSD。','A−B=10、A−D=5、B−D=15，皆小於 LSD。'],'LSD=t(.025,16)√[475(1/5+1/5)]','=T.INV.2T(.05,16)*SQRT(475*(1/5+1/5))','方案 C 顯著高於 A、B、D；其餘三組未達顯著。','若成本與可行性相近，C 是有統計證據支持的較高產出方案。',['未先確認整體 ANOVA 顯著','拿平均差直接除以 MSE']),
Q('ch14-books','simple-regression','Quan1150(Chap14)Q-set.pdf · Problem 1',3,'S','calculation','7 本書的頁數 x 與價格 y 建立最小平方法。計算結果 b₀≈1.0416、b₁≈0.009907、R²≈0.5629。哪個解讀正確？',['每增加 1 頁，預測價格平均增加約 $0.0099；頁數解釋約 56.3% 價格變異','每增加 $1，頁數增加 0.0099 頁','頁數造成 56.3% 的價格','模型可安全預測任意頁數'],0,['迴歸式 ŷ=1.0416+0.009907x。','Slope 的單位是「美元／頁」。','R²=.5629 表示樣本中價格變異約 56.3% 被線性模型解釋。','相關 r=+√R²≈.7503。'],'ŷ=1.0416+0.009907x','=SLOPE(price_range,page_range); =RSQ(price_range,page_range)','斜率為正；F≈6.439，df=(1,5)，α=.10 下可拒絕 β₁=0。','頁數與書價呈正線性關係，但不能直接說頁數造成價格。',['顛倒 x/y 單位','把 R² 寫成因果比例']),
Q('ch14-flash','simple-regression','Quan1150(Chap14)Q-set.pdf · Problem 3',2,'S','calculation','Flash drive 價格與每日銷量的估計式為 ŷ=29.7857−0.7286x，R²≈.8556。若價格增加 $1，如何解讀？',['每日預測銷量平均減少約 0.729 個','每日銷量增加 29.786 個','價格減少 0.729 美元','R² 減少 72.9%'],0,['Slope b₁=−0.7286，單位是「個／美元」。','其餘條件下，在觀察價格範圍內，每增加 $1，預測銷量平均少約 .729。','r≈−.925，顯示強負線性關係。'],'ŷ=29.7857−0.7286x','=SLOPE(units_range,price_range)','α=.01 時 F≈29.62，支持線性關係。','價格較高與較低銷量相關，但觀察資料不能單獨證明價格的因果效果。',['忽略負號','把截距當成目前銷量']),
Q('ch15-sales','multiple-regression','Quan1150(Chap15)Q-set.pdf · Problem 6',3,'S','calculation','銷售（百萬美元）模型：ŷ=7.0174+8.6233X₁+0.0858X₂；X₁=廣告（百萬美元）、X₂=業務員數。X₁=3.5、X₂=45 時預測銷售？',['約 41.06 百萬美元','約 37.19 百萬美元','約 48.77 百萬美元','約 4106 美元'],0,['代入：7.0174+8.6233(3.5)+0.0858(45)。','=7.0174+30.18155+3.861=41.05995。','Y 單位是 million dollars，因此為約 41.06 百萬美元。'],'ŷ=7.0174+8.6233X₁+0.0858X₂','=7.0174+8.6233*3.5+0.0858*45','模型整體 F≈17.73，df=(2,7)，在 α=.05 顯著；R²≈.835。','在輸入條件下模型預測銷售約 4,106 萬美元。',['忘記 Y 的百萬美元單位','把 X₁ 的 3.5 寫成 3,500,000']),
Q('ch15-coefficients','multiple-regression','Quan1150(Chap15)Q-set.pdf · Problem 6(d)',2,'S','interpretation','同一模型中，廣告係數 8.6233（SE=2.3968），業務員係數 .0858（SE=.1845），df=7。α=.05 下何者顯著？',['兩者都顯著','只有廣告 X₁ 顯著','只有業務員 X₂ 顯著','兩者都不顯著'],1,['t₁=8.6233/2.3968≈3.598。','t₂=.0858/.1845≈.465。','雙尾 tcrit(df=7,.05)≈2.365；故只拒絕 β₁=0。'],'tⱼ=bⱼ/SE(bⱼ)','=T.DIST.2T(ABS(t),7)','控制業務員數後，廣告係數顯著；控制廣告後，業務員數不顯著。','目前資料支持廣告與銷售的線性關係，沒有足夠證據確認業務員數的額外效果。',['看到整體 F 顯著就說每個 X 顯著','忘記雙尾']),
Q('ch16-add','model-building','Quan1150(Chap16)Q-set.pdf · Problem 10',3,'A','calculation','n=28；加入 X₃ 前 SSE=1425，加入後 SSE=1300。完整模型有 3 個 predictors。Partial F 約多少？應否在 α=.05 加入 X₃？',['F≈2.31，不加入','F≈9.23，加入','F≈0.52，不加入','F≈125，加入'],0,['reduced 與 full 相差 1 個 predictor。','full error df=28−3−1=24。','F=[(1425−1300)/1]/(1300/24)=2.3077。','Fcrit(1,24,.05)≈4.26，故不拒絕 β₃=0。'],'F=[(SSEᵣ−SSE𝒻)/q]/[SSE𝒻/(n−p𝒻−1)]','=(1425-1300)/(1300/24)','新增 X₃ 所降低的 SSE 未達統計顯著。','除非有很強的商業或理論理由，模型不必因這份資料加入 X₃。',['分母用 reduced SSE','忘記 full model 的 intercept df']),
Q('ch16-dw','model-building','Quan1150(Model Construction).pdf · Section 16.5 / Jefe de Cocina',2,'A','interpretation','時間序列迴歸的 Durbin–Watson d=0.319；n=20、k=1 時 dL=1.20、dU=1.41。正自相關檢定結論？',['有正自相關證據','無自相關','有負自相關','結果不確定'],0,['正自相關規則：若 d<dL，拒絕無正自相關。','.319<1.20，因此落在正自相關區。','殘差不是獨立，原迴歸的標準推論需要重新評估。'],'d=Σ(eₜ−eₜ₋₁)²/Σeₜ²','依時間排序 residual 後計算','有顯著正一階自相關的證據。','前一期未解釋因素會延續到下一期；原模型可能漏掉時間結構。',['把 d 接近 0 說成無自相關','落在界線區仍硬判']),
Q('ch17-wma','forecasting','Quan1150(Chap17)Q-set.pdf · Problem 2',2,'A','calculation','用最近三個月需求預測 7 月；4–6 月需求為 60、75、87，權重由舊到新為 2、3、5。7 月 weighted moving average？',['74.0','78.0','80.5','87.0'],1,['總權重=2+3+5=10。','加權總和=60(2)+75(3)+87(5)=780。','7 月預測=780/10=78。'],'FJul=[2(Apr)+3(May)+5(Jun)]/10','=SUMPRODUCT({60,75,87},{2,3,5})/10','7 月預測需求為 78。','近期 6 月得到最大權重，因此預測較接近近期高需求。',['最大權重放在最舊資料','忘記除以權重總和']),
Q('ch17-es','forecasting','Quan1150(Chap17)Q-set.pdf · Problem 5',2,'A','calculation','1–4 月實際銷售為 18、23、20、16；α=.2，1 月初始預測=18。5 月預測是多少？',['18.00','18.56','19.20','16.51'],1,['F₂=.2(18)+.8(18)=18。','F₃=.2(23)+.8(18)=19。','F₄=.2(20)+.8(19)=19.2。','F₅=.2(16)+.8(19.2)=18.56。'],'Fₜ₊₁=αYₜ+(1−α)Fₜ','逐列建立 Actual、Forecast、Error','5 月 one-step-ahead forecast 為 18.56。','模型平滑了 4 月的下降，因此預測仍高於 16。',['用未來 actual 更新同一期 forecast','把 α 當百分比 20']),
Q('ch18-sign','nonparametric','Quan1150Chap18)Q-set.pdf · Problem 1',2,'A','calculation','400 人中 250 偏好國產酒、140 偏好歐洲酒、10 無偏好。Sign test 的有效 n、μ、σ 約為？',['n=400, μ=200, σ=10','n=390, μ=195, σ=9.874','n=390, μ=250, σ=140','n=400, μ=195, σ=9.874'],1,['ties（無偏好）排除，所以 n=250+140=390。','H₀:p=.5 下 μ=np=195。','σ=√[np(1−p)]=√97.5≈9.874。'],'μ=n/2; σ=√n/2','=SQRT(390)/2','z 約 (250−195)/9.874=5.57，雙尾 p 極小，拒絕偏好相同。','樣本顯示國產酒與歐洲酒的偏好比例不同，且國產酒較高。',['把 ties 算進 n','把 250 與 140 當成兩獨立樣本']),
Q('ch18-spearman','nonparametric','Quan1150Chap18)Q-set.pdf · Problem 8',2,'A','calculation','兩位雇主對 5 位候選人的排名差平方和 Σd²=10。Spearman rₛ 為何？',['0.50','−0.50','0.90','10.00'],0,['n=5、Σd²=10。','rₛ=1−6(10)/[5(25−1)]。','=1−60/120=.50。'],'rₛ=1−6Σd²/[n(n²−1)]','=1-6*10/(5*(5^2-1))','rₛ=.50；n=5 時未達 α=.05 雙尾顯著門檻。','兩位雇主排名有中度正向一致，但樣本太小，證據不足。',['把 d 相加後再平方','將中度相關寫成完全一致'])
];

const METHOD_TABLE=[['類別分配是否符合預期','一個類別變數的 counts','Chi-square goodness-of-fit'],['兩個類別變數是否相關','r×c 列聯表','Chi-square independence'],['三組以上平均數','數值 Y＋一個類別 factor','One-way ANOVA'],['控制區集後比較處理','數值 Y＋treatment＋block','Randomized block ANOVA'],['一個 X 解釋／預測 Y','兩個數值變數','Simple regression'],['多個 X 共同解釋 Y','數值 Y＋多個 X','Multiple regression'],['時間序列預測下一期','依時間排列的數值','Moving average / smoothing'],['兩獨立組、序位或非常態','兩組 ranks','Mann–Whitney U'],['成對前後、序位或非常態','paired differences','Wilcoxon signed-rank']];
const SOURCES=[
  ['2026Quan_syll.pdf','Fall 2026 syllabus；期末範圍 Chapters 12–18。'],['Quan1150(Chap12)Q-set.pdf','47 選擇題＋35 problems；無年度、配分與答案。'],['Quan1150(Chap13)Q-set.pdf','68 選擇題＋47 problems；含 CRD、block、factorial、LSD。'],['Quan1150(Chap14)Q-set.pdf','113 選擇題＋33 problems；簡單迴歸與輸出解讀。'],['Quan1150(Chap15)Q-set.pdf','約 85 選擇題＋30 problems；複迴歸、t/F、R²。'],['Quan1150(Chap16)Q-set.pdf','48 選擇題＋29 problems；模型建構與新增變數。'],['Quan1150(Chap17)Q-set.pdf','37 選擇題＋31 problems；預測與時間序列。'],['Quan1150Chap18)Q-set.pdf','53 選擇題＋28 problems；無母數方法。']
];
const COMMON_MISTAKES=['選錯統計方法：先看資料型態與樣本結構，不要先看數字大小。','H₀ / H₁ 寫反，或只寫符號不寫商業對象。','把「不拒絕 H₀」寫成「接受 H₀ 為真」。','只報 p-value，沒有比較 α、沒有 decision。','卡方與 F 忘記自由度，或把右尾檢定做成雙尾。','ANOVA 顯著後直接宣稱每一組都不同。','整體 regression F 顯著就說所有 X 都顯著。','把相關或觀察性迴歸解讀成因果。','只寫統計數字，沒有回答原本的商業問題。','忘記單位：千元、百萬美元、每頁、每位業務員。'];
const SPRINT_PLANS={7:['Day 1：Chi-square 題型辨識、E 與 df','Day 2：ANOVA table、F 與 LSD','Day 3：Simple regression、r、R²、殘差','Day 4：Multiple regression 的整體 F 與個別 t','Day 5：Model construction 與 Durbin–Watson','Day 6：Forecasting 與 Nonparametric','Day 7：限時模擬＋只複習錯題'],3:['Day 1：S 級 Chi-square＋ANOVA','Day 2：Regression Chapters 14–16','Day 3：Forecasting＋Nonparametric＋模擬考'],1:['上午：所有決策樹與假設模板','下午：S 級代表題各做 2 題','晚上：錯題本、公式與 Excel 函數'],60:['0–10 分：方法選擇總表','10–25 分：Chi-square / ANOVA df 與公式','25–40 分：Regression t / F / R²','40–50 分：Forecast / Nonparametric','50–60 分：錯題與商業結論句型']};
